import os
from dotenv import load_dotenv
load_dotenv()

MODEL_PATH = '../models/yolov8n-pose_int8_vela.tflite'
UART_PORT = '/dev/ttyLP1'
BAUD_RATE = 115200
# Lowered threshold slightly to accommodate scaled confidence
CONF_THRESHOLD = 0.4
NMS_THRESHOLD = 0.4
IMG_SIZE = 320
DISPLAY_SIZE = 640
DISPLAY_SCALE = DISPLAY_SIZE / IMG_SIZE
C270_FOV = 60
CAMERA_FY = 1414.5829053415814
CAMERA_CY = 394.3216966345815

HOST_IP = '0.0.0.0'
PORT = 9999

# Motor control settings
MOTOR_I2C_BUS = 0
MOTOR_I2C_ADDRESS = 0x40
ENABLE_MOTOR_OUTPUT = True
PAN_MAX_DELTA = 30.0
TILT_MAX_DELTA = 45.0
TILT_MIN_DELTA = 45.0

DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")

# Event logging
LOG_ENABLED = True
LOG_THROTTLE_SECONDS = 1.5
LOG_DETECTION_EVENTS = True
LOG_STATE_EVENTS = True
LOG_ANGLE_EVENTS = True
LOG_API_EVENTS = True
LOG_ERROR_EVENTS = True
LOG_MOTOR_EVENTS = False
LOG_NOW_ANGLE = False

# FSM scanning
SCAN_STEP_DEGREES = 2
SCAN_SETTLE_SECONDS = 0.18
