import os

MODEL_PATH = '../models/yolov8n-pose_int8_vela.tflite'
UART_PORT = '/dev/ttyLP1'
BAUD_RATE = 115200
# Lowered threshold slightly to accommodate scaled confidence
CONF_THRESHOLD = 0.4
NMS_THRESHOLD = 0.4
IMG_SIZE = 320
DISPLAY_SIZE = 640
DISPLAY_SCALE = DISPLAY_SIZE / IMG_SIZE
C270_FOV = 60
HOST_IP = '0.0.0.0'
PORT = 9999

# Motor control settings for camera pan/tilt/height
MOTOR_PAN_CHANNEL = 0
MOTOR_TILT_CHANNEL = 4
MOTOR_HEIGHT_CHANNEL = 8
MOTOR_I2C_BUS = 0
MOTOR_I2C_ADDRESS = 0x40
PAN_CENTER_ANGLE = 90
TILT_CENTER_ANGLE = 90
HEIGHT_CENTER_ANGLE = 90
PAN_ANGLE_RANGE = 40
TILT_ANGLE_RANGE = 35
HEIGHT_ANGLE_RANGE = 35

DISCORD_WEBHOOK_URL=os.getenv("DISCORD_WEBHOOK_URL")