import os
from dotenv import load_dotenv
load_dotenv()

MODEL_PATH = '../models/yolov8n-pose_int8_vela.tflite'
UART_PORT = '/dev/ttyLP1'
BAUD_RATE = 115200
# Lowered threshold slightly to accommodate scaled confidence
CONF_THRESHOLD = 0.4
NMS_THRESHOLD = 0.4
IMG_SIZE = 320
DISPLAY_SIZE = 640
DISPLAY_SCALE = DISPLAY_SIZE / IMG_SIZE
C270_FOV = 60
CAMERA_FY = 1414.5829053415814
CAMERA_CY = 394.3216966345815

HOST_IP = '0.0.0.0'
PORT = 9999

# Motor control settings
MOTOR_I2C_BUS = 0
MOTOR_I2C_ADDRESS = 0x40
ENABLE_MOTOR_OUTPUT = True
PAN_MAX_DELTA = 45.0
TILT_MAX_DELTA = 45.0
TILT_MIN_DELTA = 45.0

# Stepper X-axis settings
ENABLE_STEPPER_OUTPUT = True
STEPPER_GPIOCHIP = "/dev/gpiochip0"
STEPPER_STEP_LINE = 18
STEPPER_DIR_LINE = 17
STEPPER_BOTTOM_SWITCH_LINE = 15
STEPPER_BOTTOM_SWITCH_ACTIVE_LOW = True
STEPPER_STEP_HIGH_TIME = 0.0005
STEPPER_STEP_LOW_TIME = 0.0010
STEPPER_STEPS_PER_CM = 1000.0
STEPPER_ROD_LENGTH_CM = 21.0
STEPPER_PHOTO_COUNT = 3
STEPPER_UP_DIRECTION = 0
STEPPER_HOME_DIRECTION = 1
STEPPER_MAX_HOME_CM = 24.0
STEPPER_HOME_BACKOFF_STEPS = 200

# RGB LED settings
ENABLE_LED_OUTPUT = True
LED_GPIOCHIP = "/dev/gpiochip0"
LED_R_LINE = 3
LED_G_LINE = 2
LED_B_LINE = 14
LED_COMMON_ANODE = True
LED_BLINK_INTERVAL_SECONDS = 0.25

DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")

# Event logging
LOG_ENABLED = True
LOG_THROTTLE_SECONDS = 1.5
LOG_DETECTION_EVENTS = True
LOG_STATE_EVENTS = True
LOG_ANGLE_EVENTS = True
LOG_API_EVENTS = True
LOG_ERROR_EVENTS = True
LOG_MOTOR_EVENTS = False
LOG_NOW_ANGLE = False

# FSM scanning
SCAN_STEP_DEGREES = 2
SCAN_SETTLE_SECONDS = 0.18
HORIZONTAL_FIX_RIGHT_OFFSET_DEGREES = -7.0
