from config import HORIZONTAL_SCAN_STEP_DEGREES

STATE_SETTING = "SETTING"
STATE_MANUAL_CONTROL = "MANUAL_CONTROL"
STATE_AUTO_CONTROL = "AUTO_CONTROL"
STATE_HORIZONTAL_SWEEP = "HORIZONTAL_SWEEP"
STATE_HORIZONTAL_FIX = "HORIZONTAL_FIX"
STATE_VERTICAL_SWEEP = "VERTICAL_SWEEP"
STATE_VERTICAL_FIX = "VERTICAL_FIX"
STATE_FAILURE = "FAILURE"
STATE_PHOTO_CAPTURE = "PHOTO_CAPTURE"

SCAN_PAN_ANGLES = list(range(0, 181, HORIZONTAL_SCAN_STEP_DEGREES))
SCAN_TILT_ANGLES = list(range(60, 151, 2))
FAILURE_TIMEOUT_SECONDS = 5.0
